import React, { useState, useEffect } from 'react';
import { BarChart3, Users, Building2, DollarSign, Globe, FileText, Plus, Trash2, Edit, Eye, Wifi, WifiOff, Zap, Wallet, History, Send, Settings, Route, LogOut } from 'lucide-react';
import axios from 'axios';
const API = 'http://192.95.36.154:3001';

function App() {
  const [token, setToken] = useState(localStorage.getItem('token'));
  const [menu, setMenu] = useState('dashboard');
  const [clients, setClients] = useState([]);
  const [suppliers, setSuppliers] = useState([]);
  const [rates, setRates] = useState([]);
  const [mccMnc, setMccMnc] = useState([]);
  const [routes, setRoutes] = useState([]);
  const [messages, setMessages] = useState([]);
  const [bindStatus, setBindStatus] = useState({});
  const [toast, setToast] = useState('');
  const [loginError, setLoginError] = useState('');

  const [showAddClient, setShowAddClient] = useState(false);
  const [showAddSupplier, setShowAddSupplier] = useState(false);
  const [showAddRate, setShowAddRate] = useState(false);
  const [showAddMcc, setShowAddMcc] = useState(false);
  const [showAddRoute, setShowAddRoute] = useState(false);
  const [nrt, setNrt] = useState({name:'',prefix:'',supplierId:'',priority:1});
  const [showTopup, setShowTopup] = useState(null);
  const [showSupTopup, setShowSupTopup] = useState(null);
  const [showTx, setShowTx] = useState(null);
  const [showSupTx, setShowSupTx] = useState(null);
  const [editClient, setEditClient] = useState(null);
  const [editSupplier, setEditSupplier] = useState(null);
  const [viewCreds, setViewCreds] = useState(null);
  const [txs, setTxs] = useState([]);
  const [allTxs, setAllTxs] = useState([]);
  const [allSupTxs, setAllSupTxs] = useState([]);
  const [supTxs, setSupTxs] = useState([]);

  const [nc, setNc] = useState({name:'',balance:100,smppSystemId:'',smppPassword:''});
  const [ns, setNs] = useState({name:'',type:'SMPP',host:'',port:2775,systemId:'',password:''});
  const [nr, setNr] = useState({country:'',countryCode:'',price:0.005,type:'SENDING'});
  const [nm, setNm] = useState({country:'',countryCode:'',mcc:'',mnc:'',operator:'All'});
  const [amt, setAmt] = useState({amount:100,note:'',method:'MANUAL'});
  const [newMsg, setNewMsg] = useState({to:'',content:''});
  const [sendClient, setSendClient] = useState('');
  const [sendSupplier, setSendSupplier] = useState('');

  const auth = () => ({ headers: { Authorization: `Bearer ${token}` } });
  const msg = (m) => { setToast(m); setTimeout(()=>setToast(''),3000); };

  useEffect(() => {
    if (token) { fetchAll(); fetchBinds(); }
    const int = setInterval(fetchBinds, 15000);
    return () => clearInterval(int);
  }, [token]);

  const fetchAll = () => { fetchClients(); fetchSuppliers(); fetchRates(); fetchMcc(); fetchRoutes(); fetchMessages(); };
  const fetchBinds = async () => { try { const r = await axios.get(API+'/api/bind-status', auth()); const s={}; (r.data.results||[]).forEach(x=>{s[x.id]=x.status;}); setBindStatus(s); } catch(e) {} };
  const fetchClients = async () => { try { const r = await axios.get(API+'/api/clients', auth()); setClients(r.data.clients||[]); } catch(e) {} };
  const fetchSuppliers = async () => { try { const r = await axios.get(API+'/api/suppliers', auth()); setSuppliers(r.data.suppliers||[]); } catch(e) {} };
  const fetchRates = async () => { try { const r = await axios.get(API+'/api/rates', auth()); setRates(r.data.rates||[]); } catch(e) {} };
  const fetchMcc = async () => { try { const r = await axios.get(API+'/api/mcc-mnc', auth()); setMccMnc(r.data.rates||[]); } catch(e) {} };
  const fetchRoutes = async () => { try { const r = await axios.get(API+'/api/routes', auth()); setRoutes(r.data.routes||[]); } catch(e) {} };
  const fetchMessages = async () => { try { const r = await axios.get(API+'/api/messages?limit=200', auth()); setMessages(r.data.messages||[]); } catch(e) {} };
  const fetchTx = async (cid) => { try { const r = await axios.get(API+'/api/clients/'+cid+'/transactions', auth()); setTxs(r.data.transactions||[]); } catch(e) {} };
  const fetchSupTx = async (sid) => { try { const r = await axios.get(API+'/api/suppliers/'+sid+'/transactions', auth()); setSupTxs(r.data.transactions||[]); } catch(e) {} };
  const fetchAllPayments = async () => { try { const r1 = await axios.get(API+'/api/billing/client', auth()); setAllTxs(r1.data.billings||[]); } catch(e) {} try { const r2 = await axios.get(API+'/api/billing/supplier', auth()); setAllSupTxs(r2.data.billings||[]); } catch(e) {} };

  const login = async () => { try { const r = await axios.post(API+'/api/auth/login', { email: 'admin@smsgateway.com', password: 'admin123' }); localStorage.setItem('token', r.data.token); setToken(r.data.token); } catch(e) { setLoginError('Cannot connect'); } };

  const addClient = async () => { try { await axios.post(API+'/api/clients', {name:nc.name,balance:parseFloat(nc.balance),smppSystemId:nc.smppSystemId,smppPassword:nc.smppPassword}, auth()); setShowAddClient(false); fetchClients(); msg('Client added!'); } catch(e) { msg('Error'); } };
  const updateClient = async () => { try { await axios.put(API+'/api/clients/'+editClient.id, editClient, auth()); setEditClient(null); fetchClients(); msg('Updated!'); } catch(e) { msg('Error'); } };
  const delClient = async (id) => { if(confirm('Delete?')){ await axios.delete(API+'/api/clients/'+id, auth()); fetchClients(); } };
  const addSupplier = async () => { try { await axios.post(API+'/api/suppliers', ns, auth()); setShowAddSupplier(false); fetchSuppliers(); msg('Added!'); } catch(e) { msg('Error'); } };
  const updateSupplier = async () => { try { await axios.put(API+'/api/suppliers/'+editSupplier.id, editSupplier, auth()); setEditSupplier(null); fetchSuppliers(); msg('Updated!'); } catch(e) { msg('Error'); } };
  const delSupplier = async (id) => { if(confirm('Delete?')){ await axios.delete(API+'/api/suppliers/'+id, auth()); fetchSuppliers(); } };
  const addRate = async () => { try { await axios.post(API+'/api/rates', nr, auth()); setShowAddRate(false); fetchRates(); msg('Rate added!'); } catch(e) { msg('Error'); } };
  const addRoute = async () => { try { await axios.post(API+'/api/routes', nrt, auth()); setShowAddRoute(false); setNrt({name:'',prefix:'',supplierId:'',priority:1}); fetchRoutes(); msg('Route added!'); } catch(e) { msg('Error'); } };
  const delRoute = async (id) => { if(confirm('Delete?')){ await axios.delete(API+'/api/routes/'+id, auth()); fetchRoutes(); } };
  const delRate = async (id) => { if(confirm('Delete?')){ await axios.delete(API+'/api/rates/'+id, auth()); fetchRates(); } };
  const addMcc = async () => { try { await axios.post(API+'/api/mcc-mnc', nm, auth()); setShowAddMcc(false); fetchMcc(); msg('MCC added!'); } catch(e) { msg('Error'); } };
  const delMcc = async (id) => { if(confirm('Delete?')){ await axios.delete(API+'/api/mcc-mnc/'+id, auth()); fetchMcc(); } };
  const clientTopup = async () => { try { await axios.post(API+'/api/clients/'+showTopup+'/topup', {amount:parseFloat(amt.amount),description:amt.note||'Funds added',paymentMethod:amt.method||'MANUAL'}, auth()); setShowTopup(null); fetchClients(); msg('Funds added!'); } catch(e) { msg('Error: '+(e.response?.data?.error||e.message)); } };
  const supplierTopup = async () => { try { await axios.post(API+'/api/suppliers/'+showSupTopup+'/topup', {amount:parseFloat(amt.amount),description:amt.note||'Credit added',paymentMethod:amt.method||'MANUAL'}, auth()); setShowSupTopup(null); fetchSuppliers(); msg('Credit added!'); } catch(e) { msg('Error: '+(e.response?.data?.error||e.message)); } };
  const viewCred = async (cid) => { try { const r=await axios.get(API+'/api/clients/'+cid+'/credentials', auth()); setViewCreds(r.data); } catch(e) { msg('Error'); } };

  if (!token) {
    return <div className="min-h-screen bg-gray-950 flex items-center justify-center"><div className="bg-gray-900 p-10 rounded-2xl border border-gray-700 max-w-sm w-full text-center"><Zap className="w-16 h-16 text-emerald-400 mx-auto mb-4"/><h1 className="text-3xl font-bold text-white">Enterprise SMS</h1>{loginError&&<div className="bg-red-900/50 text-red-300 p-3 rounded-xl mb-4 text-xs">{loginError}</div>}<button onClick={login} className="w-full bg-emerald-600 text-white font-semibold py-3 rounded-xl">LOGIN</button></div></div>;
  }

  const menus = [
    {id:'dashboard',l:'Dashboard',i:<BarChart3 className="w-4 h-4"/>},{id:'clients',l:'Clients',i:<Users className="w-4 h-4"/>},
    {id:'suppliers',l:'Suppliers',i:<Building2 className="w-4 h-4"/>},{id:'routing',l:'Routing',i:<Route className="w-4 h-4"/>},
    {id:'rates',l:'Rates',i:<DollarSign className="w-4 h-4"/>},{id:'mccmnc',l:'MCC/MNC',i:<Globe className="w-4 h-4"/>},
    {id:'messages',l:'SMS Logs',i:<FileText className="w-4 h-4"/>},{id:'send',l:'Send SMS',i:<Send className="w-4 h-4"/>},
    {id:'force',l:'Force DLR',i:<Settings className="w-4 h-4"/>},
    {id:'payments',l:'Payments',i:<Wallet className="w-4 h-4"/>},
  ];

  return (
    <div className="min-h-screen bg-gray-950 text-gray-100 flex">
      {toast&&<div className="fixed top-4 right-4 z-50 bg-emerald-600 text-white px-6 py-3 rounded-xl shadow-lg text-sm">{toast}</div>}
      <div className="w-56 bg-black border-r border-gray-800 p-4 hidden lg:block min-h-screen">
        <div className="flex items-center gap-2 mb-6"><Zap className="w-6 h-6 text-emerald-400"/><span className="font-bold">Enterprise SMS</span></div>
        {menus.map(m=>(<button key={m.id} onClick={()=>setMenu(m.id)} className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-sm mb-1 ${menu===m.id?'bg-emerald-600 text-white':'text-gray-400 hover:bg-gray-800'}`}>{m.i}{m.l}</button>))}
        <button onClick={()=>{localStorage.removeItem('token');setToken(null);}} className="w-full text-gray-500 hover:text-red-400 mt-6 text-sm"><LogOut className="w-4 h-4 inline"/> Logout</button>
      </div>
      <div className="flex-1 p-6 overflow-auto">
        
        {/* DASHBOARD */}
        {menu==='dashboard'&&<div><h1 className="text-2xl font-bold mb-4">Dashboard</h1>
          <div className="grid grid-cols-4 gap-3 mb-4">
            {[{l:'Clients',v:clients.length},{l:'Suppliers',v:suppliers.length},{l:'MCC/MNC',v:mccMnc.length},{l:'Routes',v:routes.length},{l:'Rates',v:rates.length},{l:'Messages',v:messages.length},{l:'Bound',v:Object.values(bindStatus).filter(s=>s==='BIND').length}].map((s,i)=>(<div key={i} className="bg-gray-900 p-4 rounded-2xl border border-gray-800"><div className="text-gray-500 text-xs">{s.l}</div><div className="text-2xl font-bold mt-1">{s.v}</div></div>))}
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-gray-900 p-4 rounded-2xl"><h3 className="text-sm font-semibold mb-2">Bind Status</h3>
              {suppliers.map(s=>(<div key={s.id} className="flex justify-between py-1 text-xs"><span>{s.name}</span><span className={bindStatus[s.id]==='BIND'?'text-emerald-400':'text-red-400'}>● {bindStatus[s.id]||'?'}</span></div>))}
              {clients.filter(c=>c.smppAccounts?.length>0).slice(0,10).map(c=>(<div key={c.id} className="flex justify-between py-1 text-xs"><span>{c.name}</span><span className={bindStatus[c.id]==='BIND'?'text-emerald-400':'text-red-400'}>● {bindStatus[c.id]||'?'}</span></div>))}
            </div>
            <div className="bg-gray-900 p-4 rounded-2xl"><h3 className="text-sm font-semibold mb-2">Recent Messages</h3>
              {messages.slice(0,10).map(m=>(<div key={m.id} className="flex justify-between py-1 text-xs border-b border-gray-800"><span className="text-emerald-300">{m.to}</span><span>{m.content?.substring(0,20)}</span><span className={m.status==='DELIVERED'?'text-emerald-400':'text-yellow-400'}>{m.status}</span></div>))}
            </div>
          </div>
        </div>}

        {/* CLIENTS */}
        {menu==='clients'&&<div>
          <div className="flex justify-between mb-3"><h1 className="text-2xl font-bold">Clients</h1><button onClick={()=>setShowAddClient(true)} className="bg-emerald-600 px-4 py-2 rounded-xl text-sm flex items-center gap-2"><Plus className="w-4 h-4"/>Add</button></div>
          {showAddClient&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold mb-4">New Client</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Name*" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nc.name} onChange={e=>setNc({...nc,name:e.target.value})}/><input type="number" placeholder="Balance" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nc.balance} onChange={e=>setNc({...nc,balance:e.target.value})}/><input placeholder="System ID" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nc.smppSystemId} onChange={e=>setNc({...nc,smppSystemId:e.target.value})}/><input placeholder="Password" type="password" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nc.smppPassword} onChange={e=>setNc({...nc,smppPassword:e.target.value})}/></div><div className="flex gap-2 mt-4"><button onClick={addClient} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Save</button><button onClick={()=>setShowAddClient(false)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
          {editClient&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold mb-4">Edit Client</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Name" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editClient.name||''} onChange={e=>setEditClient({...editClient,name:e.target.value})}/><input type="number" placeholder="Balance" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editClient.balance||0} onChange={e=>setEditClient({...editClient,balance:e.target.value})}/></div><div className="flex gap-2 mt-4"><button onClick={updateClient} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Update</button><button onClick={()=>setEditClient(null)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
          <div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Name</th><th className="p-3">System ID</th><th className="p-3">Balance</th><th className="p-3">Credit</th><th className="p-3">Bind</th><th className="p-3">Actions</th></tr></thead><tbody>{clients.map(c=>(<tr key={c.id} className="border-b border-gray-800"><td className="p-3">{c.name}</td><td className="p-3 text-xs text-emerald-400">{c.smppAccounts?.[0]?.systemId||'-'}</td><td className="p-3 font-mono">${c.balance?.toFixed(2)}</td><td className="p-3 font-mono">${(c.credit||50000).toFixed(0)}</td><td className="p-3">{bindStatus[c.id]==='BIND'?<span className="text-emerald-400">● BIND</span>:<span className="text-red-400">● UNBIND</span>}</td><td className="p-3 flex gap-1"><button onClick={()=>setEditClient(c)} className="text-blue-400"><Edit className="w-3.5 h-3.5"/></button><button onClick={()=>viewCred(c.id)} className="text-purple-400"><Eye className="w-3.5 h-3.5"/></button><button onClick={()=>{setShowTopup(c.id);setAmt({amount:100});}} className="text-amber-400"><Wallet className="w-3.5 h-3.5"/></button><button onClick={()=>{setShowTx(c.id);fetchTx(c.id);}} className="text-blue-400"><History className="w-3.5 h-3.5"/></button><button onClick={()=>delClient(c.id)} className="text-red-400"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>))}</tbody></table></div>
        </div>}

        {/* SUPPLIERS */}
        {menu==='suppliers'&&<div>
          <div className="flex justify-between mb-3"><h1 className="text-2xl font-bold">Suppliers</h1><button onClick={()=>setShowAddSupplier(true)} className="bg-emerald-600 px-4 py-2 rounded-xl text-sm flex items-center gap-2"><Plus className="w-4 h-4"/>Add</button></div>
          {showAddSupplier&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold mb-4">New Supplier</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Name*" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={ns.name} onChange={e=>setNs({...ns,name:e.target.value})}/><select className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={ns.type} onChange={e=>setNs({...ns,type:e.target.value})}><option>SMPP</option><option>HTTP</option></select><input placeholder="Host" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={ns.host} onChange={e=>setNs({...ns,host:e.target.value})}/><input type="number" placeholder="Port" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={ns.port} onChange={e=>setNs({...ns,port:e.target.value})}/><input placeholder="System ID" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={ns.systemId} onChange={e=>setNs({...ns,systemId:e.target.value})}/><input placeholder="Password" type="password" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={ns.password} onChange={e=>setNs({...ns,password:e.target.value})}/></div><div className="flex gap-2 mt-4"><button onClick={addSupplier} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Save</button><button onClick={()=>setShowAddSupplier(false)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
          {editSupplier&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold mb-4">Edit Supplier</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Name" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editSupplier.name||''} onChange={e=>setEditSupplier({...editSupplier,name:e.target.value})}/><input placeholder="Host" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editSupplier.smppConnections?.[0]?.host||''} onChange={e=>{const sc=[...(editSupplier.smppConnections||[])];if(sc[0])sc[0]={...sc[0],host:e.target.value};setEditSupplier({...editSupplier,smppConnections:sc});}}/><input placeholder="System ID" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editSupplier.smppConnections?.[0]?.systemId||''} onChange={e=>{const sc=[...(editSupplier.smppConnections||[])];if(sc[0])sc[0]={...sc[0],systemId:e.target.value};setEditSupplier({...editSupplier,smppConnections:sc});}}/><input placeholder="Password" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editSupplier.smppConnections?.[0]?.password||''} onChange={e=>{const sc=[...(editSupplier.smppConnections||[])];if(sc[0])sc[0]={...sc[0],password:e.target.value};setEditSupplier({...editSupplier,smppConnections:sc});}}/></div><div className="flex gap-2 mt-4"><button onClick={updateSupplier} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Update</button><button onClick={()=>setEditSupplier(null)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
          <div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Name</th><th className="p-3">Host:Port</th><th className="p-3">System ID</th><th className="p-3">Balance</th><th className="p-3">Credit</th><th className="p-3">Bind</th><th className="p-3">Actions</th></tr></thead><tbody>{suppliers.map(s=>(<tr key={s.id} className="border-b border-gray-800"><td className="p-3">{s.name}</td><td className="p-3 text-xs">{s.smppConnections?.[0]?.host}:{s.smppConnections?.[0]?.port}</td><td className="p-3 text-xs text-emerald-400">{s.smppConnections?.[0]?.systemId}</td><td className="p-3 font-mono">${(s.balance||0).toFixed(2)}</td><td className="p-3 font-mono">${(s.creditLimit||0).toFixed(2)}</td><td className="p-3">{bindStatus[s.id]==='BIND'?<span className="text-emerald-400">● BIND</span>:<span className="text-red-400">● UNBIND</span>}</td><td className="p-3 flex gap-1"><button onClick={()=>setEditSupplier(s)} className="text-blue-400"><Edit className="w-3.5 h-3.5"/></button><button onClick={()=>{setShowSupTopup(s.id);setAmt({amount:100});}} className="text-amber-400"><Wallet className="w-3.5 h-3.5"/></button><button onClick={()=>{setShowSupTx(s.id);fetchSupTx(s.id);}} className="text-blue-400"><History className="w-3.5 h-3.5"/></button><button onClick={()=>delSupplier(s.id)} className="text-red-400"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>))}</tbody></table></div>
        </div>}

        {/* MCC/MNC */}
        {menu==='mccmnc'&&<div>
          <div className="flex justify-between mb-3"><h1 className="text-2xl font-bold">MCC/MNC</h1><button onClick={()=>setShowAddMcc(true)} className="bg-emerald-600 px-4 py-2 rounded-xl text-sm flex items-center gap-2"><Plus className="w-4 h-4"/>Add</button></div>
          {showAddMcc&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold mb-4">Add MCC/MNC</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Country" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nm.country} onChange={e=>setNm({...nm,country:e.target.value})}/><input placeholder="Code" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nm.countryCode} onChange={e=>setNm({...nm,countryCode:e.target.value})}/><input placeholder="MCC" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nm.mcc} onChange={e=>setNm({...nm,mcc:e.target.value})}/><input placeholder="MNC" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nm.mnc} onChange={e=>setNm({...nm,mnc:e.target.value})}/></div><div className="flex gap-2 mt-4"><button onClick={addMcc} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Save</button><button onClick={()=>setShowAddMcc(false)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
          <div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Country</th><th className="p-3">Code</th><th className="p-3">MCC</th><th className="p-3">MNC</th><th className="p-3">Del</th></tr></thead><tbody>{mccMnc.length>0?mccMnc.map(r=>(<tr key={r.id} className="border-b border-gray-800"><td className="p-3">{r.country}</td><td className="p-3 text-emerald-400">+{r.countryCode}</td><td className="p-3">{r.mcc}</td><td className="p-3">{r.mnc}</td><td className="p-3"><button onClick={()=>delMcc(r.id)} className="text-red-400"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>)):<tr><td colSpan="5" className="p-8 text-center text-gray-500">No data. Click Add to create.</td></tr>}</tbody></table></div>
        </div>}

        {/* ROUTING */}
        {menu==='routing'&&<div>
          <div className="flex justify-between mb-3"><h1 className="text-2xl font-bold">Routing</h1><button onClick={()=>setShowAddRoute(true)} className="bg-emerald-600 px-4 py-2 rounded-xl text-sm flex items-center gap-2"><Plus className="w-4 h-4"/>Add Route</button></div>
          {showAddRoute&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-[500px]"><h3 className="font-semibold mb-4">New Route</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Route Name *" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nrt.name} onChange={e=>setNrt({...nrt,name:e.target.value})}/><input placeholder="Prefix (*=all, 1=US, 44=UK)" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nrt.prefix} onChange={e=>setNrt({...nrt,prefix:e.target.value})}/><select className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nrt.supplierId} onChange={e=>setNrt({...nrt,supplierId:e.target.value})}><option value="">Select Supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name} ({s.type})</option>)}</select><input type="number" placeholder="Priority (1=highest)" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nrt.priority} onChange={e=>setNrt({...nrt,priority:e.target.value})}/></div><div className="flex gap-2 mt-4"><button onClick={addRoute} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Save</button><button onClick={()=>setShowAddRoute(false)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
          <div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Pri</th><th className="p-3">Route Name</th><th className="p-3">Prefix</th><th className="p-3">Supplier</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{routes.length>0?routes.map(r=>(<tr key={r.id} className="border-b border-gray-800 hover:bg-gray-800/50"><td className="p-3"><span className={`px-2 py-0.5 rounded text-xs font-bold ${r.priority===1?'bg-amber-900 text-amber-400':'bg-gray-800 text-gray-400'}`}>P{r.priority}</span></td><td className="p-3 font-medium">{r.name}</td><td className="p-3 text-emerald-400 font-mono">{r.prefix}</td><td className="p-3">{r.supplier?.name||'-'}</td><td className="p-3"><span className={`px-3 py-1 rounded-full text-xs ${r.status==='ACTIVE'?'bg-emerald-900 text-emerald-400':'bg-red-900 text-red-400'}`}>{r.status||'ACTIVE'}</span></td><td className="p-3 flex gap-2"><button onClick={()=>delRoute(r.id)} className="text-red-400"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>)):<tr><td colSpan="6" className="p-8 text-center text-gray-500">No routes configured. Click Add Route to create one.</td></tr>}</tbody></table></div>
        </div>}

{/* RATES, MESSAGES, SEND, FORCE DLR - Simple versions */}
        {menu==='rates'&&<div><div className="flex justify-between mb-3"><h1 className="text-2xl font-bold">Rates</h1><button onClick={()=>setShowAddRate(true)} className="bg-emerald-600 px-4 py-2 rounded-xl text-sm flex items-center gap-2"><Plus className="w-4 h-4"/>Add</button></div>{showAddRate&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold mb-4">Add Rate</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Country" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nr.country} onChange={e=>setNr({...nr,country:e.target.value})}/><input placeholder="Code" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nr.countryCode} onChange={e=>setNr({...nr,countryCode:e.target.value})}/><input type="number" step="0.0001" placeholder="Price" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={nr.price} onChange={e=>setNr({...nr,price:e.target.value})}/></div><div className="flex gap-2 mt-4"><button onClick={addRate} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Save</button><button onClick={()=>setShowAddRate(false)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}<div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Country</th><th className="p-3">Code</th><th className="p-3">Price</th><th className="p-3">Del</th></tr></thead><tbody>{rates.map(r=>(<tr key={r.id} className="border-b border-gray-800"><td className="p-3">{r.country}</td><td className="p-3 text-emerald-400">+{r.countryCode}</td><td className="p-3 text-amber-400">${r.price?.toFixed(4)}</td><td className="p-3"><button onClick={()=>delRate(r.id)} className="text-red-400"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>))}</tbody></table></div></div>}
        {menu==='messages'&&<div><h1 className="text-2xl font-bold mb-3">SMS Logs</h1><div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Time</th><th className="p-3">To</th><th className="p-3">Content</th><th className="p-3">Status</th></tr></thead><tbody>{messages.map(m=>(<tr key={m.id} className="border-b border-gray-800"><td className="p-3 text-xs">{new Date(m.submittedAt).toLocaleString()}</td><td className="p-3 text-emerald-300">{m.to}</td><td className="p-3 max-w-[200px] truncate">{m.content}</td><td className="p-3"><span className={`px-2 py-0.5 rounded-full text-xs ${m.status==='DELIVERED'?'bg-emerald-900 text-emerald-400':'bg-yellow-900 text-yellow-400'}`}>{m.status}</span></td></tr>))}</tbody></table></div></div>}
        {menu==='send'&&<div className="max-w-lg mx-auto"><h1 className="text-2xl font-bold mb-3">Send SMS</h1><div className="bg-gray-900 p-6 rounded-2xl space-y-3">
            <div><label className="text-xs text-gray-400 mb-1 block">Client (Sender)</label><select className="w-full bg-black border border-gray-700 rounded-xl px-4 py-2 text-sm" value={sendClient} onChange={e=>setSendClient(e.target.value)}><option value="">Select Client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name} (${c.balance?.toFixed(2)})</option>)}</select></div>
            <div><label className="text-xs text-gray-400 mb-1 block">Supplier (Route)</label><select className="w-full bg-black border border-gray-700 rounded-xl px-4 py-2 text-sm" value={sendSupplier} onChange={e=>setSendSupplier(e.target.value)}><option value="">Auto Route</option>{suppliers.filter(s=>s.status==='ACTIVE').map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>
            <div><label className="text-xs text-gray-400 mb-1 block">To (Destination)</label><input className="w-full bg-black border border-gray-700 rounded-xl px-4 py-2 text-sm" value={newMsg.to} onChange={e=>setNewMsg({...newMsg,to:e.target.value})} placeholder="+15551234567"/></div>
            <div><label className="text-xs text-gray-400 mb-1 block">Message</label><textarea className="w-full bg-black border border-gray-700 rounded-xl px-4 py-2 text-sm h-24" value={newMsg.content} onChange={e=>setNewMsg({...newMsg,content:e.target.value})} placeholder="Message..."/></div>
            <button onClick={async()=>{try{await axios.post(API+'/api/messages/send',{to:newMsg.to,content:newMsg.content,clientId:sendClient||undefined,supplierId:sendSupplier||undefined},auth());msg('Sent!');setNewMsg({to:'',content:''});}catch(e){msg('Error: '+(e.response?.data?.error||e.message));}}} className="w-full bg-emerald-600 py-2 rounded-xl text-sm">SEND SMS</button></div></div>}

        {menu==='payments'&&<div>
          <h1 className="text-2xl font-bold mb-3">Payment History</h1>
          <button onClick={fetchAllPayments} className="bg-emerald-600 px-4 py-2 rounded-xl text-sm mb-4">Load All Payments</button>
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-gray-900 rounded-2xl p-4"><h3 className="text-sm font-semibold mb-2">Client Transactions</h3><div className="max-h-96 overflow-auto"><table className="w-full text-xs"><thead><tr className="border-b border-gray-800 text-gray-400"><th className="p-2">Date</th><th className="p-2">Client</th><th className="p-2">Type</th><th className="p-2">Amount</th></tr></thead><tbody>{clients.map(c=>{return c.transactions?c.transactions.map(t=>(<tr key={t.id} className="border-b border-gray-800"><td className="p-2 text-gray-400">{new Date(t.createdAt).toLocaleString()}</td><td className="p-2">{c.name}</td><td className="p-2"><span className={`px-2 py-0.5 rounded text-xs ${t.type==='TOPUP'?'bg-emerald-900 text-emerald-400':'bg-red-900 text-red-400'}`}>{t.type}</span></td><td className={`p-2 ${t.amount>0?'text-emerald-400':'text-red-400'}`}>${t.amount?.toFixed(2)}</td></tr>)):null})}</tbody></table></div></div>
            <div className="bg-gray-900 rounded-2xl p-4"><h3 className="text-sm font-semibold mb-2">Supplier Transactions</h3><div className="max-h-96 overflow-auto"><table className="w-full text-xs"><thead><tr className="border-b border-gray-800 text-gray-400"><th className="p-2">Date</th><th className="p-2">Supplier</th><th className="p-2">Amount</th></tr></thead><tbody>{allSupTxs.length>0?allSupTxs.slice(0,50).map(t=>(<tr key={t.id} className="border-b border-gray-800"><td className="p-2 text-gray-400">{new Date(t.submittedAt||t.createdAt).toLocaleString()}</td><td className="p-2">{t.supplier?.name||'N/A'}</td><td className="p-2 text-amber-400">${t.cost?.toFixed(4)}</td></tr>)):<tr><td colSpan="3" className="p-4 text-center text-gray-500">Click Load All Payments</td></tr>}</tbody></table></div></div>
          </div>
        </div>}

{/* MODALS */}
        {showTopup&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold mb-4">Add Client Funds</h3><input type="number" placeholder="Amount *" className="w-full bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm mb-3" value={amt.amount} onChange={e=>setAmt({...amt,amount:e.target.value})}/><input placeholder="Note (e.g. Bank Transfer, Payment)" className="w-full bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm mb-3" value={amt.note||''} onChange={e=>setAmt({...amt,note:e.target.value})}/><select className="w-full bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm mb-3" value={amt.method||'MANUAL'} onChange={e=>setAmt({...amt,method:e.target.value})}><option value="BANK_TRANSFER">Bank Transfer</option><option value="CREDIT_CARD">Credit Card</option><option value="PAYPAL">PayPal</option><option value="CRYPTO">Crypto</option><option value="MANUAL">Manual</option></select><div className="flex gap-2"><button onClick={clientTopup} className="bg-emerald-600 px-4 py-2 rounded-lg text-sm flex-1">Confirm Topup</button><button onClick={()=>setShowTopup(null)} className="bg-gray-700 px-4 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
        {showSupTopup&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold mb-4">Add Supplier Credit</h3><input type="number" placeholder="Amount *" className="w-full bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm mb-3" value={amt.amount} onChange={e=>setAmt({...amt,amount:e.target.value})}/><input placeholder="Note (e.g. Prepaid Credit)" className="w-full bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm mb-3" value={amt.note||''} onChange={e=>setAmt({...amt,note:e.target.value})}/><select className="w-full bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm mb-3" value={amt.method||'MANUAL'} onChange={e=>setAmt({...amt,method:e.target.value})}><option value="BANK_TRANSFER">Bank Transfer</option><option value="CREDIT_CARD">Credit Card</option><option value="PAYPAL">PayPal</option><option value="MANUAL">Manual</option></select><div className="flex gap-2"><button onClick={supplierTopup} className="bg-emerald-600 px-4 py-2 rounded-lg text-sm flex-1">Confirm Topup</button><button onClick={()=>setShowSupTopup(null)} className="bg-gray-700 px-4 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
        {showTx&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-[500px] max-h-[400px] overflow-auto"><h3 className="font-semibold mb-4">Payment History</h3><table className="w-full text-xs"><tbody>{txs.map(t=>(<tr key={t.id} className="border-b border-gray-800"><td className="p-2 text-gray-400">{new Date(t.createdAt).toLocaleString()}</td><td className="p-2">{t.type}</td><td className="p-2">${t.amount?.toFixed(2)}</td></tr>))}</tbody></table><button onClick={()=>setShowTx(null)} className="mt-4 bg-gray-700 px-4 py-2 rounded-lg text-sm w-full">Close</button></div></div>}
        {showSupTx&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-[500px] max-h-[400px] overflow-auto"><h3 className="font-semibold mb-4">Supplier Payment History</h3><table className="w-full text-xs"><tbody>{supTxs.map(t=>(<tr key={t.id} className="border-b border-gray-800"><td className="p-2 text-gray-400">{new Date(t.createdAt).toLocaleString()}</td><td className="p-2">{t.type}</td><td className="p-2">${t.amount?.toFixed(2)}</td></tr>))}</tbody></table><button onClick={()=>setShowSupTx(null)} className="mt-4 bg-gray-700 px-4 py-2 rounded-lg text-sm w-full">Close</button></div></div>}
        {viewCreds&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold mb-4">{viewCreds.name}</h3>{viewCreds.smpp?.map((s,i)=>(<div key={i} className="p-3 bg-black rounded-lg mb-2"><div>ID: <span className="text-emerald-400">{s.systemId}</span></div><div>Pass: <span className="text-emerald-400">{s.password}</span></div></div>))}<button onClick={()=>setViewCreds(null)} className="bg-gray-700 px-4 py-2 rounded-lg text-sm w-full mt-3">Close</button></div></div>}
      </div>
    </div>
  );
}
export default App;
