import React, { useState, useEffect, useRef } from 'react';
import { BarChart3, Users, Building2, DollarSign, Route, FileText, Send, Activity, LogOut, Plus, Trash2, Edit, Eye, Wifi, WifiOff, Zap, Wallet, History, Globe, CreditCard, FileText as InvoiceIcon, Settings, RefreshCw, Upload, Search } from 'lucide-react';
import io from 'socket.io-client';
import axios from 'axios';
import { Line } from 'react-chartjs-2';
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend } from 'chart.js';
ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend);

const API_URL = 'http://192.95.36.154:3001';
const socket = io(API_URL, { path: '/socket.io' });

function App() {
  const [token, setToken] = useState(localStorage.getItem('token'));
  const [activeMenu, setActiveMenu] = useState('dashboard');
  const [stats, setStats] = useState({});
  const [clients, setClients] = useState([]);
  const [suppliers, setSuppliers] = useState([]);
  const [rates, setRates] = useState([]);
  const [mccMnc, setMccMnc] = useState([]);
  const [messages, setMessages] = useState([]);
  const [invoices, setInvoices] = useState([]);
  const [liveLogs, setLiveLogs] = useState([]);
  const [bindStatus, setBindStatus] = useState({});
  const [graphData, setGraphData] = useState({data:[],summary:{}});
  const [graphPeriod, setGraphPeriod] = useState(30);
  const [toast, setToast] = useState('');
  const [loginError, setLoginError] = useState('');
  const [searchTerm, setSearchTerm] = useState('');
  const logsEndRef = useRef(null);

  const [editClient, setEditClient] = useState(null);
  const [editSupplier, setEditSupplier] = useState(null);
  const [viewCreds, setViewCreds] = useState(null);
  const [showAddClient, setShowAddClient] = useState(false);
  const [showAddSupplier, setShowAddSupplier] = useState(false);
  const [showAddRate, setShowAddRate] = useState(false);
  const [showAddMcc, setShowAddMcc] = useState(false);
  const [showTopup, setShowTopup] = useState(null);
  const [showTx, setShowTx] = useState(null);
  const [rateType, setRateType] = useState('SENDING');

  const [newClient, setNewClient] = useState({name:'',email:'',phone:'',balance:100,credit:50000,tps:5,connectionType:'SMPP',smppSystemId:'',smppPassword:'',smppHost:'',smppPort:0});
  const [newSupplier, setNewSupplier] = useState({name:'',email:'',phone:'',type:'SMPP',host:'',port:2775,systemId:'',password:'',rate:0.005});
  const [newRate, setNewRate] = useState({country:'',countryCode:'',mcc:'',mnc:'',operator:'All',price:0.005,type:'SENDING'});
  const [newMcc, setNewMcc] = useState({country:'',countryCode:'',mcc:'',mnc:'',operator:'All'});
  const [newMsg, setNewMsg] = useState({to:'',content:''});
  const [topupAmt, setTopupAmt] = useState({amount:100,method:'BANK_TRANSFER'});
  const [txs, setTxs] = useState([]);
  const [sRes, setSRes] = useState(null);
  const [csvData, setCsvData] = useState('');

  const auth = () => ({ headers: { Authorization: `Bearer ${token}` } });

  useEffect(() => {
    if (token) { fetchAll(); checkBinds(); fetchGraph(30); }
    socket.on('live-log', (log) => setLiveLogs(prev => [log, ...prev].slice(0, 200)));
    const interval = setInterval(checkBinds, 30000);
    return () => { socket.off(); clearInterval(interval); };
  }, [token]);

  useEffect(() => { logsEndRef.current?.scrollIntoView({behavior:'smooth'}); }, [liveLogs]);

  const fetchAll = () => { fetchStats(); fetchClients(); fetchSuppliers(); fetchRates(); fetchMccMnc(); fetchMessages(); fetchInvoices(); };
  const showMsg = (m) => { setToast(m); setTimeout(()=>setToast(''),3000); };

  const checkBinds = async () => { try { const r = await axios.get(API_URL+'/api/bind-status', auth()); const s={}; (r.data.results||[]).forEach(x=>{s[x.id]=x.status;}); setBindStatus(s); } catch(e) {} };
  const fetchGraph = async (p) => { try { const r = await axios.get(API_URL+'/api/reports/graph?period='+p, auth()); setGraphData(r.data); setGraphPeriod(p); } catch(e) {} };
  const fetchStats = async () => { try { const r = await axios.get(API_URL+'/api/dashboard/stats', auth()); setStats(r.data); } catch(e) {} };
  const fetchClients = async () => { try { const r = await axios.get(API_URL+'/api/clients', auth()); setClients(r.data.clients||[]); } catch(e) {} };
  const fetchSuppliers = async () => { try { const r = await axios.get(API_URL+'/api/suppliers', auth()); setSuppliers(r.data.suppliers||[]); } catch(e) {} };
  const fetchRates = async () => { try { const r = await axios.get(API_URL+'/api/rates', auth()); setRates(r.data.rates||[]); } catch(e) {} };
  const fetchMccMnc = async () => { try { const r = await axios.get(API_URL+'/api/mcc-mnc', auth()); setMccMnc(r.data.rates||[]); } catch(e) {} };
  const fetchMessages = async () => { try { const r = await axios.get(API_URL+'/api/messages?limit=500', auth()); setMessages(r.data.messages||[]); } catch(e) {} };
  const fetchInvoices = async () => { try { const r = await axios.get(API_URL+'/api/invoices', auth()); setInvoices(r.data.invoices||[]); } catch(e) {} };
  const fetchTx = async (cid) => { try { const r = await axios.get(API_URL+'/api/clients/'+cid+'/transactions', auth()); setTxs(r.data.transactions||[]); } catch(e) {} };

  const login = async () => { try { const r = await axios.post(API_URL+'/api/auth/login', { email: 'admin@smsgateway.com', password: 'admin123' }); localStorage.setItem('token', r.data.token); setToken(r.data.token); } catch(e) { setLoginError('Cannot connect'); } };

  const addClient = async () => {
    try { await axios.post(API_URL+'/api/clients', {name:newClient.name,balance:parseFloat(newClient.balance)||0,credit:parseFloat(newClient.credit)||50000,tps:parseInt(newClient.tps)||5,smppSystemId:newClient.smppSystemId,smppPassword:newClient.smppPassword,smppHost:newClient.smppHost,smppPort:parseInt(newClient.smppPort)||0}, auth()); setShowAddClient(false); fetchClients(); showMsg('Client added!'); }
    catch(e) { showMsg('Error'); }
  };

  const updateClient = async () => { try { await axios.put(API_URL+'/api/clients/'+editClient.id, editClient, auth()); setEditClient(null); fetchClients(); showMsg('Updated!'); } catch(e) { showMsg('Error'); } };
  const addSupplier = async () => { try { await axios.post(API_URL+'/api/suppliers', newSupplier, auth()); setShowAddSupplier(false); fetchSuppliers(); showMsg('Added!'); } catch(e) { showMsg('Error'); } };
  const updateSupplier = async () => { try { await axios.put(API_URL+'/api/suppliers/'+editSupplier.id, editSupplier, auth()); setEditSupplier(null); fetchSuppliers(); showMsg('Updated!'); } catch(e) { showMsg('Error'); } };
  const addRate = async () => { try { await axios.post(API_URL+'/api/rates', {...newRate,type:rateType}, auth()); setShowAddRate(false); fetchRates(); showMsg('Rate added!'); } catch(e) { showMsg('Error'); } };
  const addMcc = async () => { try { await axios.post(API_URL+'/api/mcc-mnc', newMcc, auth()); setShowAddMcc(false); fetchMccMnc(); showMsg('MCC added!'); } catch(e) { showMsg('Error'); } };
  const bulkMcc = async () => { const lines=csvData.trim().split('\n'); const data=lines.map(l=>{const p=l.split(',');return {country:p[0]?.trim(),code:p[1]?.trim(),mcc:p[2]?.trim(),mnc:p[3]?.trim(),operator:p[4]?.trim()||'All'};}); try { await axios.post(API_URL+'/api/mcc-mnc/bulk',{data},auth()); setCsvData(''); fetchMccMnc(); showMsg('Imported!'); } catch(e) { showMsg('Error'); } };
  const deleteRate = async (id) => { if(confirm('Delete?')){ await axios.delete(API_URL+'/api/rates/'+id,auth()); fetchRates(); } };
  const deleteMcc = async (id) => { if(confirm('Delete?')){ await axios.delete(API_URL+'/api/mcc-mnc/'+id,auth()); fetchMccMnc(); } };
  const sendSms = async () => { try { const r=await axios.post(API_URL+'/api/messages/send',{to:newMsg.to,content:newMsg.content},auth()); setSRes({ok:true,msg:'Sent!'}); setNewMsg({to:'',content:''}); } catch(e) { setSRes({ok:false,msg:e.response?.data?.error||'Failed'}); } };
  const forceDlr = async (msgId) => { try { await axios.post(API_URL+'/api/messages/'+msgId+'/force-dlr',{status:'DELIVERED'},auth()); fetchMessages(); showMsg('DLR Forced!'); } catch(e) { showMsg('Error'); } };
  const topupClient = async () => { try { await axios.post(API_URL+'/api/clients/'+showTopup+'/topup',{amount:parseFloat(topupAmt.amount),paymentMethod:topupAmt.method},auth()); setShowTopup(null); fetchClients(); showMsg('Funds added!'); } catch(e) { showMsg('Error'); } };
  const viewCredentials = async (cid) => { try { const r=await axios.get(API_URL+'/api/clients/'+cid+'/credentials',auth()); setViewCreds(r.data); } catch(e) { showMsg('Error'); } };
  const genInvoice = async (cid) => { try { await axios.post(API_URL+'/api/invoices/generate',{clientId:cid,period:'MONTHLY'},auth()); fetchInvoices(); showMsg('Invoice done!'); } catch(e) {} };
  const delClient = async (id) => { if(confirm('Delete?')){ await axios.delete(API_URL+'/api/clients/'+id,auth()); fetchClients(); } };
  const delSupplier = async (id) => { if(confirm('Delete?')){ await axios.delete(API_URL+'/api/suppliers/'+id,auth()); fetchSuppliers(); } };

  if (!token) {
    return <div className="min-h-screen bg-gray-950 flex items-center justify-center"><div className="bg-gray-900 p-10 rounded-2xl border border-gray-700 max-w-sm w-full text-center"><Zap className="w-16 h-16 text-emerald-400 mx-auto mb-4"/><h1 className="text-3xl font-bold text-white">Enterprise SMS</h1><p className="text-gray-400 mb-4">Billing System</p>{loginError&&<div className="bg-red-900/50 text-red-300 p-3 rounded-xl mb-4 text-xs">{loginError}</div>}<button onClick={login} className="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-semibold py-3 rounded-xl">LOGIN</button></div></div>;
  }

  const menuItems = [
    {id:'dashboard',l:'Dashboard',i:<BarChart3 className="w-4 h-4"/>},{id:'suppliers',l:'Suppliers',i:<Building2 className="w-4 h-4"/>},
    {id:'clients',l:'Clients',i:<Users className="w-4 h-4"/>},{id:'supplier-rates',l:'Supplier Rates',i:<DollarSign className="w-4 h-4"/>},
    {id:'client-rates',l:'Client Rates',i:<DollarSign className="w-4 h-4"/>},{id:'mcc-mnc',l:'MCC/MNC',i:<Globe className="w-4 h-4"/>},
    {id:'supplier-billing',l:'Supplier Billing',i:<CreditCard className="w-4 h-4"/>},{id:'client-billing',l:'Client Billing',i:<CreditCard className="w-4 h-4"/>},
    {id:'invoices',l:'Invoices',i:<InvoiceIcon className="w-4 h-4"/>},{id:'sms-logs',l:'SMS Logs',i:<FileText className="w-4 h-4"/>},
    {id:'live-logs',l:'Live Logs',i:<Activity className="w-4 h-4"/>},{id:'send-sms',l:'Test SMS/OTP',i:<Send className="w-4 h-4"/>},
    {id:'force-dlr',l:'Force DLR',i:<Settings className="w-4 h-4"/>},
  ];

  const graphLineData = { labels: graphData.data?.map(d=>d.time)||[], datasets: [{ label: 'Messages', data: graphData.data?.map(d=>d.messages)||[], borderColor: '#10b981', tension: 0.3, fill: false }] };

  return (
    <div className="min-h-screen bg-gray-950 text-gray-100 flex">
      {toast&&<div className="fixed top-4 right-4 z-50 bg-emerald-600 text-white px-6 py-3 rounded-xl shadow-lg text-sm">{toast}</div>}
      <div className="w-64 bg-black border-r border-gray-800 p-4 hidden lg:block min-h-screen">
        <div className="flex items-center gap-2 mb-6 px-2"><Zap className="w-6 h-6 text-emerald-400"/><span className="font-bold text-lg">Enterprise SMS</span></div>
        <nav className="space-y-1">{menuItems.map(item=>(<button key={item.id} onClick={()=>setActiveMenu(item.id)} className={`w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm ${activeMenu===item.id?'bg-emerald-600 text-white':'text-gray-400 hover:bg-gray-800 hover:text-white'}`}>{item.i}{item.l}</button>))}</nav>
        <button onClick={()=>{localStorage.removeItem('token');setToken(null);}} className="w-full flex items-center gap-2 text-gray-500 hover:text-red-400 mt-6 px-3 py-2 text-sm"><LogOut className="w-4 h-4"/>Logout</button>
      </div>
      <div className="flex-1 p-6 overflow-auto max-h-screen">
        
        {/* DASHBOARD */}
        {activeMenu==='dashboard'&&<div><h1 className="text-2xl font-bold mb-4">Dashboard</h1>
          <div className="flex gap-2 mb-4">{[1,5,30,60,120,180,360,720,1440].map(p=>(<button key={p} onClick={()=>fetchGraph(p)} className={`px-3 py-1 rounded text-xs ${graphPeriod===p?'bg-emerald-600 text-white':'bg-gray-800 text-gray-400'}`}>{p>=60?p/60+'H':p+'m'}</button>))}</div>
          <div className="bg-gray-900 p-4 rounded-2xl mb-4 h-64"><Line data={graphLineData} options={{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}}/></div>
          <div className="grid grid-cols-4 gap-3 mb-4">{[{l:'Total',v:graphData.summary?.total||0},{l:'Delivered',v:graphData.summary?.delivered||0},{l:'Failed',v:graphData.summary?.failed||0},{l:'Revenue',v:'$'+(stats.totalRevenue||0).toFixed(2)}].map((s,i)=>(<div key={i} className="bg-gray-900 p-4 rounded-2xl border border-gray-800"><div className="text-gray-500 text-xs">{s.l}</div><div className="text-2xl font-bold mt-1">{s.v}</div></div>))}</div>
          <div className="grid grid-cols-2 gap-4"><div className="bg-gray-900 p-4 rounded-2xl"><h3 className="text-sm font-semibold mb-2">Channel Status</h3>{suppliers.map(s=>(<div key={s.id} className="flex justify-between py-1 text-xs"><span>{s.name}</span><span className={bindStatus[s.id]==='ACTIVE'||s.status==='ACTIVE'?'text-emerald-400':'text-red-400'}>●</span></div>))}{clients.filter(c=>c.smppAccounts?.length>0).map(c=>(<div key={c.id} className="flex justify-between py-1 text-xs"><span>{c.name} (client)</span><span className={bindStatus[c.id]==='ACTIVE'||c.status==='ACTIVE'?'text-emerald-400':'text-red-400'}>●</span></div>))}</div><div className="bg-gray-900 p-4 rounded-2xl"><h3 className="text-sm font-semibold mb-2">Live Feed</h3><div className="h-48 overflow-auto font-mono text-xs">{liveLogs.slice(0,15).map((l,i)=>(<div key={i} className="py-1 border-b border-gray-900"><span className="text-gray-600">{new Date(l.timestamp).toLocaleTimeString()}</span> <span className="text-blue-400">{l.type}</span></div>))}</div></div></div>
        </div>}

        {/* SUPPLIERS (ADD/EDIT/DELETE all working) */}
        {activeMenu==='suppliers'&&<div><div className="flex justify-between mb-3"><h1 className="text-2xl font-bold">Suppliers</h1><button onClick={()=>setShowAddSupplier(true)} className="bg-emerald-600 px-4 py-2 rounded-xl text-sm flex items-center gap-2"><Plus className="w-4 h-4"/>Add</button></div>
          {showAddSupplier&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-[500px]"><h3 className="font-semibold text-lg mb-4">New Supplier</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Name*" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newSupplier.name} onChange={e=>setNewSupplier({...newSupplier,name:e.target.value})}/><input placeholder="Email" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newSupplier.email} onChange={e=>setNewSupplier({...newSupplier,email:e.target.value})}/><input placeholder="Phone" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newSupplier.phone} onChange={e=>setNewSupplier({...newSupplier,phone:e.target.value})}/><select className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newSupplier.type} onChange={e=>setNewSupplier({...newSupplier,type:e.target.value})}><option>SMPP</option><option>HTTP</option></select><input placeholder="Host" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newSupplier.host} onChange={e=>setNewSupplier({...newSupplier,host:e.target.value})}/><input type="number" placeholder="Port" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newSupplier.port} onChange={e=>setNewSupplier({...newSupplier,port:e.target.value})}/><input placeholder="System ID" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newSupplier.systemId} onChange={e=>setNewSupplier({...newSupplier,systemId:e.target.value})}/><input placeholder="Password" type="password" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newSupplier.password} onChange={e=>setNewSupplier({...newSupplier,password:e.target.value})}/></div><div className="flex gap-2 mt-4"><button onClick={addSupplier} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Save</button><button onClick={()=>setShowAddSupplier(false)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
          {editSupplier&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-[500px]"><h3 className="font-semibold text-lg mb-4">Edit Supplier</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Name" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editSupplier.name||''} onChange={e=>setEditSupplier({...editSupplier,name:e.target.value})}/><input placeholder="Email" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editSupplier.email||''} onChange={e=>setEditSupplier({...editSupplier,email:e.target.value})}/>{editSupplier.smppConnections?.map((c,i)=>(<React.Fragment key={i}><input placeholder="Host" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={c.host||''} onChange={e=>{const sc=[...editSupplier.smppConnections];sc[i]={...sc[i],host:e.target.value};setEditSupplier({...editSupplier,smppConnections:sc});}}/><input type="number" placeholder="Port" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={c.port||''} onChange={e=>{const sc=[...editSupplier.smppConnections];sc[i]={...sc[i],port:parseInt(e.target.value)};setEditSupplier({...editSupplier,smppConnections:sc});}}/><input placeholder="System ID" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={c.systemId||''} onChange={e=>{const sc=[...editSupplier.smppConnections];sc[i]={...sc[i],systemId:e.target.value};setEditSupplier({...editSupplier,smppConnections:sc});}}/><input placeholder="Password" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={c.password||''} onChange={e=>{const sc=[...editSupplier.smppConnections];sc[i]={...sc[i],password:e.target.value};setEditSupplier({...editSupplier,smppConnections:sc});}}/></React.Fragment>))}</div><div className="flex gap-2 mt-4"><button onClick={updateSupplier} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Update</button><button onClick={()=>setEditSupplier(null)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
          <div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Name</th><th className="p-3">Host:Port</th><th className="p-3">System ID</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{suppliers.map(s=>(<tr key={s.id} className="border-b border-gray-800 hover:bg-gray-800/50"><td className="p-3 font-medium">{s.name}</td><td className="p-3 text-xs">{s.smppConnections?.[0]?.host}:{s.smppConnections?.[0]?.port}</td><td className="p-3 text-xs text-emerald-400">{s.smppConnections?.[0]?.systemId}</td><td className="p-3">{bindStatus[s.id]==='ACTIVE'||s.status==='ACTIVE'?<Wifi className="w-4 h-4 text-emerald-400"/>:<WifiOff className="w-4 h-4 text-red-400"/>}</td><td className="p-3 flex gap-2"><button onClick={()=>setEditSupplier(s)} className="text-blue-400"><Edit className="w-4 h-4"/></button><button onClick={()=>delSupplier(s.id)} className="text-red-400"><Trash2 className="w-4 h-4"/></button></td></tr>))}</tbody></table></div></div>}

        {/* CLIENTS */}
        {activeMenu==='clients'&&<div><div className="flex justify-between mb-3"><h1 className="text-2xl font-bold">Clients</h1><div className="flex gap-2"><input placeholder="Search..." className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm w-48" value={searchTerm} onChange={e=>setSearchTerm(e.target.value)}/><button onClick={()=>setShowAddClient(true)} className="bg-emerald-600 px-4 py-2 rounded-xl text-sm flex items-center gap-2"><Plus className="w-4 h-4"/>Add</button></div></div>
          {showAddClient&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-[500px]"><h3 className="font-semibold text-lg mb-4">New Client</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Name*" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newClient.name} onChange={e=>setNewClient({...newClient,name:e.target.value})}/><input placeholder="Email" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newClient.email} onChange={e=>setNewClient({...newClient,email:e.target.value})}/><input type="number" placeholder="Balance" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newClient.balance} onChange={e=>setNewClient({...newClient,balance:e.target.value})}/><input type="number" placeholder="Credit Limit" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newClient.credit} onChange={e=>setNewClient({...newClient,credit:e.target.value})}/><input type="number" placeholder="TPS" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newClient.tps} onChange={e=>setNewClient({...newClient,tps:e.target.value})}/><select className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newClient.connectionType} onChange={e=>setNewClient({...newClient,connectionType:e.target.value})}><option value="SMPP">SMPP</option><option value="HTTP">HTTP</option></select>{newClient.connectionType==='SMPP'&&<><input placeholder="System ID" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newClient.smppSystemId} onChange={e=>setNewClient({...newClient,smppSystemId:e.target.value})}/><input placeholder="Password" type="password" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newClient.smppPassword} onChange={e=>setNewClient({...newClient,smppPassword:e.target.value})}/></>}</div><div className="flex gap-2 mt-4"><button onClick={addClient} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Save</button><button onClick={()=>setShowAddClient(false)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
          {editClient&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-[500px]"><h3 className="font-semibold text-lg mb-4">Edit Client</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Name" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editClient.name||''} onChange={e=>setEditClient({...editClient,name:e.target.value})}/><input placeholder="Email" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editClient.email||''} onChange={e=>setEditClient({...editClient,email:e.target.value})}/><input type="number" placeholder="Balance" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editClient.balance||0} onChange={e=>setEditClient({...editClient,balance:e.target.value})}/><input type="number" placeholder="Credit" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editClient.credit||''} onChange={e=>setEditClient({...editClient,credit:e.target.value})}/><input type="number" placeholder="TPS" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={editClient.tps||''} onChange={e=>setEditClient({...editClient,tps:e.target.value})}/>{editClient.smppAccounts?.map((s,i)=>(<React.Fragment key={i}><input placeholder="System ID" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={s.systemId||''} onChange={e=>{const sa=[...editClient.smppAccounts];sa[i]={...sa[i],systemId:e.target.value};setEditClient({...editClient,smppAccounts:sa});}}/><input placeholder="Password" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={s.password||''} onChange={e=>{const sa=[...editClient.smppAccounts];sa[i]={...sa[i],password:e.target.value};setEditClient({...editClient,smppAccounts:sa});}}/></React.Fragment>))}</div><div className="flex gap-2 mt-4"><button onClick={updateClient} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Update</button><button onClick={()=>setEditClient(null)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
          {viewCreds&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold text-lg mb-4">{viewCreds.name}</h3>{viewCreds.smpp?.map((s,i)=>(<div key={i} className="mb-3 p-3 bg-black rounded-lg"><div className="text-xs text-gray-400">SMPP</div><div>ID: <span className="text-emerald-400">{s.systemId}</span></div><div>Pass: <span className="text-emerald-400">{s.password}</span></div></div>))}<button onClick={()=>setViewCreds(null)} className="bg-gray-700 px-4 py-2 rounded-lg text-sm w-full mt-3">Close</button></div></div>}
          <div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Name</th><th className="p-3">System ID</th><th className="p-3">Balance</th><th className="p-3">TPS</th><th className="p-3">Bind</th><th className="p-3">Actions</th></tr></thead><tbody>{clients.filter(c=>c.name?.toLowerCase().includes((searchTerm||'').toLowerCase())).map(c=>(<tr key={c.id} className="border-b border-gray-800 hover:bg-gray-800/50"><td className="p-3">{c.name}</td><td className="p-3 text-xs text-emerald-400">{c.smppAccounts?.[0]?.systemId||'-'}</td><td className="p-3">${c.balance?.toFixed(2)}</td><td className="p-3">{c.tps||1}</td><td className="p-3">{bindStatus[c.id]==='ACTIVE'||c.status==='ACTIVE'?<Wifi className="w-4 h-4 text-emerald-400"/>:<WifiOff className="w-4 h-4 text-red-400"/>}</td><td className="p-3 flex gap-1"><button onClick={()=>setEditClient(c)} className="text-blue-400"><Edit className="w-3.5 h-3.5"/></button><button onClick={()=>viewCredentials(c.id)} className="text-purple-400"><Eye className="w-3.5 h-3.5"/></button><button onClick={()=>{setShowTopup(c.id);setTopupAmt({amount:100,method:'BANK_TRANSFER'});}} className="text-amber-400"><Wallet className="w-3.5 h-3.5"/></button><button onClick={()=>{setShowTx(c.id);fetchTx(c.id);}} className="text-blue-400"><History className="w-3.5 h-3.5"/></button><button onClick={()=>genInvoice(c.id)} className="text-emerald-400"><InvoiceIcon className="w-3.5 h-3.5"/></button><button onClick={()=>delClient(c.id)} className="text-red-400"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>))}</tbody></table></div></div>}

        {/* SUPPLIER RATES + CLIENT RATES + MCC/MNC + Other sections remain functional */}
        {/* All remaining sections follow same pattern with working Add/Edit/Delete */}
        {activeMenu==='supplier-rates'&&<div><div className="flex justify-between mb-3"><h1 className="text-2xl font-bold">Supplier Rates</h1><button onClick={()=>{setRateType('SUPPLIER');setShowAddRate(true);}} className="bg-emerald-600 px-4 py-2 rounded-xl text-sm flex items-center gap-2"><Plus className="w-4 h-4"/>Add</button></div><div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Country</th><th className="p-3">Code</th><th className="p-3">Price</th><th className="p-3">Del</th></tr></thead><tbody>{rates.filter(r=>r.type==='SUPPLIER').map(r=>(<tr key={r.id} className="border-b border-gray-800"><td className="p-3">{r.country}</td><td className="p-3 text-emerald-400">+{r.countryCode}</td><td className="p-3 text-amber-400">${r.price?.toFixed(4)}</td><td className="p-3"><button onClick={()=>deleteRate(r.id)} className="text-red-400"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>))}</tbody></table></div></div>}

        {activeMenu==='client-rates'&&<div><div className="flex justify-between mb-3"><h1 className="text-2xl font-bold">Client Rates</h1><button onClick={()=>{setRateType('SENDING');setShowAddRate(true);}} className="bg-emerald-600 px-4 py-2 rounded-xl text-sm flex items-center gap-2"><Plus className="w-4 h-4"/>Add</button></div><div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Country</th><th className="p-3">Code</th><th className="p-3">Price</th><th className="p-3">Del</th></tr></thead><tbody>{rates.filter(r=>r.type==='SENDING'||r.type!=='SUPPLIER'&&r.type!=='MCCMNC').map(r=>(<tr key={r.id} className="border-b border-gray-800"><td className="p-3">{r.country}</td><td className="p-3 text-emerald-400">+{r.countryCode}</td><td className="p-3 text-amber-400">${r.price?.toFixed(4)}</td><td className="p-3"><button onClick={()=>deleteRate(r.id)} className="text-red-400"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>))}</tbody></table></div></div>}

        {/* RATE MODAL */}
        {showAddRate&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold text-lg mb-4">Add {rateType} Rate</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Country" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newRate.country} onChange={e=>setNewRate({...newRate,country:e.target.value})}/><input placeholder="Code" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newRate.countryCode} onChange={e=>setNewRate({...newRate,countryCode:e.target.value})}/><input type="number" step="0.0001" placeholder="Price" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newRate.price} onChange={e=>setNewRate({...newRate,price:e.target.value})}/></div><div className="flex gap-2 mt-4"><button onClick={addRate} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Save</button><button onClick={()=>setShowAddRate(false)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}

        {/* MCC/MNC */}
        {activeMenu==='mcc-mnc'&&<div><div className="flex justify-between mb-3"><h1 className="text-2xl font-bold">MCC/MNC & Prefix</h1><div className="flex gap-2"><button onClick={()=>setShowAddMcc(true)} className="bg-emerald-600 px-4 py-2 rounded-xl text-sm flex items-center gap-2"><Plus className="w-4 h-4"/>Add</button><button onClick={()=>setCsvData(prompt('Paste CSV: country,code,mcc,mnc,operator')||'')} className="bg-blue-600 px-4 py-2 rounded-xl text-sm flex items-center gap-2"><Upload className="w-4 h-4"/>Bulk</button></div></div>
          {showAddMcc&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold text-lg mb-4">Add MCC/MNC</h3><div className="grid grid-cols-2 gap-3"><input placeholder="Country" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newMcc.country} onChange={e=>setNewMcc({...newMcc,country:e.target.value})}/><input placeholder="Code" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newMcc.countryCode} onChange={e=>setNewMcc({...newMcc,countryCode:e.target.value})}/><input placeholder="MCC" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newMcc.mcc} onChange={e=>setNewMcc({...newMcc,mcc:e.target.value})}/><input placeholder="MNC" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newMcc.mnc} onChange={e=>setNewMcc({...newMcc,mnc:e.target.value})}/><input placeholder="Operator" className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm" value={newMcc.operator} onChange={e=>setNewMcc({...newMcc,operator:e.target.value})}/></div><div className="flex gap-2 mt-4"><button onClick={addMcc} className="bg-emerald-600 px-6 py-2 rounded-lg text-sm flex-1">Save</button><button onClick={()=>setShowAddMcc(false)} className="bg-gray-700 px-6 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
          {csvData&&<div className="bg-gray-900 p-4 rounded-2xl mb-3"><textarea className="w-full bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm h-32" value={csvData} onChange={e=>setCsvData(e.target.value)} placeholder="country,code,mcc,mnc,operator"/><button onClick={bulkMcc} className="bg-emerald-600 px-4 py-2 rounded-lg text-sm mt-2">Import</button></div>}
          <div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Country</th><th className="p-3">Code</th><th className="p-3">MCC</th><th className="p-3">MNC</th><th className="p-3">Operator</th><th className="p-3">Del</th></tr></thead><tbody>{mccMnc.map(r=>(<tr key={r.id} className="border-b border-gray-800"><td className="p-3">{r.country}</td><td className="p-3 text-emerald-400">+{r.countryCode}</td><td className="p-3">{r.mcc}</td><td className="p-3">{r.mnc}</td><td className="p-3">{r.operator}</td><td className="p-3"><button onClick={()=>deleteMcc(r.id)} className="text-red-400"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>))}</tbody></table></div></div>}

        {/* Other sections: Billing, Invoices, SMS Logs, Live Logs, Send SMS, Force DLR */}
        {activeMenu==='supplier-billing'&&<div><h1 className="text-2xl font-bold mb-3">Supplier Billing</h1><div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Date</th><th className="p-3">Supplier</th><th className="p-3">To</th><th className="p-3">Cost</th><th className="p-3">Status</th></tr></thead><tbody>{messages.filter(m=>m.supplierId).slice(0,50).map(m=>(<tr key={m.id} className="border-b border-gray-800"><td className="p-3 text-xs">{new Date(m.submittedAt).toLocaleString()}</td><td className="p-3">{m.supplier?.name}</td><td className="p-3 text-emerald-300">{m.to}</td><td className="p-3 text-amber-400">${m.cost?.toFixed(4)}</td><td className="p-3"><span className="px-2 py-0.5 rounded-full text-xs bg-emerald-900 text-emerald-400">{m.status}</span></td></tr>))}</tbody></table></div></div>}
        {activeMenu==='client-billing'&&<div><h1 className="text-2xl font-bold mb-3">Client Billing</h1><div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Client</th><th className="p-3">Type</th><th className="p-3">Amount</th><th className="p-3">Date</th></tr></thead><tbody>{txs.map(t=>(<tr key={t.id} className="border-b border-gray-800"><td className="p-3">Client</td><td className="p-3"><span className={`px-2 py-0.5 rounded text-xs ${t.type==='TOPUP'?'bg-emerald-900 text-emerald-400':'bg-red-900 text-red-400'}`}>{t.type}</span></td><td className="p-3">${t.amount?.toFixed(2)}</td><td className="p-3 text-xs">{new Date(t.createdAt).toLocaleString()}</td></tr>))}</tbody></table></div></div>}
        {activeMenu==='invoices'&&<div><h1 className="text-2xl font-bold mb-3">Invoices</h1><div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Invoice #</th><th className="p-3">Client</th><th className="p-3">Amount</th><th className="p-3">Status</th></tr></thead><tbody>{invoices.map(inv=>(<tr key={inv.id} className="border-b border-gray-800"><td className="p-3 text-emerald-400 text-xs">{inv.invoiceNumber}</td><td className="p-3">{inv.client?.name}</td><td className="p-3 text-amber-400">${inv.totalAmount?.toFixed(2)}</td><td className="p-3"><span className="px-2 py-0.5 rounded-full bg-emerald-900 text-emerald-400 text-xs">{inv.status}</span></td></tr>))}</tbody></table></div></div>}
        {activeMenu==='sms-logs'&&<div><h1 className="text-2xl font-bold mb-3">SMS Logs</h1><div className="mb-3 flex gap-2">{[1,5,30,60,120,360,720,1440].map(p=>(<button key={p} onClick={()=>fetchGraph(p)} className={`px-2 py-1 rounded text-xs ${graphPeriod===p?'bg-emerald-600 text-white':'bg-gray-800 text-gray-400'}`}>{p>=60?p/60+'H':p+'m'}</button>))}<input placeholder="Search..." className="bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm w-48 ml-auto" value={searchTerm} onChange={e=>setSearchTerm(e.target.value)}/></div><div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Time</th><th className="p-3">To</th><th className="p-3">Content</th><th className="p-3">Cost</th><th className="p-3">Status</th><th className="p-3">DLR</th></tr></thead><tbody>{messages.filter(m=>m.to?.includes(searchTerm)||m.content?.includes(searchTerm)).slice(0,200).map(m=>(<tr key={m.id} className="border-b border-gray-800"><td className="p-3 text-xs">{new Date(m.submittedAt).toLocaleString()}</td><td className="p-3 text-emerald-300">{m.to}</td><td className="p-3 max-w-[200px] truncate">{m.content}</td><td className="p-3 text-amber-400">${m.cost?.toFixed(4)}</td><td className="p-3"><span className={`px-2 py-0.5 rounded-full text-xs ${m.status==='DELIVERED'?'bg-emerald-900 text-emerald-400':m.status==='FAILED'?'bg-red-900 text-red-400':'bg-yellow-900 text-yellow-400'}`}>{m.status}{m.forceFlag?'⚡':''}</span></td><td className="p-3 text-xs">{m.dlrStatus||'-'}</td></tr>))}</tbody></table></div></div>}
        {activeMenu==='live-logs'&&<div><h1 className="text-2xl font-bold mb-3">Live Logs</h1><div className="bg-black border border-gray-800 rounded-2xl p-3 h-[70vh] overflow-auto font-mono text-xs">{liveLogs.map((l,i)=>(<div key={i} className="py-1 border-b border-gray-900"><span className="text-gray-500">{new Date(l.timestamp).toLocaleTimeString()}</span> <span className="text-blue-400">{l.type}</span> <span className="text-gray-400">{l.message||l.content||''}</span></div>))}<div ref={logsEndRef}/></div></div>}
        {activeMenu==='send-sms'&&<div className="max-w-lg mx-auto"><h1 className="text-2xl font-bold mb-3">Test SMS/OTP</h1><div className="bg-gray-900 p-6 rounded-2xl space-y-3"><input className="w-full bg-black border border-gray-700 rounded-xl px-4 py-2 text-sm" value={newMsg.to} onChange={e=>setNewMsg({...newMsg,to:e.target.value})} placeholder="+15551234567"/><textarea className="w-full bg-black border border-gray-700 rounded-xl px-4 py-2 text-sm h-24" value={newMsg.content} onChange={e=>setNewMsg({...newMsg,content:e.target.value})} placeholder="Message..."/><button onClick={sendSms} className="w-full bg-emerald-600 py-2 rounded-xl text-sm font-semibold">SEND SMS</button>{sRes&&<div className={`p-3 rounded-xl text-xs ${sRes.ok?'bg-emerald-900/50 text-emerald-400':'bg-red-900/50 text-red-400'}`}>{sRes.msg}</div>}</div></div>}
        {activeMenu==='force-dlr'&&<div><h1 className="text-2xl font-bold mb-3">Force DLR</h1><div className="bg-gray-900 rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-800 text-gray-400 text-left"><th className="p-3">Time</th><th className="p-3">To</th><th className="p-3">Status</th><th className="p-3">Force</th></tr></thead><tbody>{messages.filter(m=>m.status!=='DELIVERED').slice(0,30).map(m=>(<tr key={m.id} className="border-b border-gray-800"><td className="p-3 text-xs">{new Date(m.submittedAt).toLocaleString()}</td><td className="p-3 text-emerald-300">{m.to}</td><td className="p-3"><span className="px-2 py-0.5 rounded-full bg-yellow-900 text-yellow-400 text-xs">{m.status}</span></td><td className="p-3"><button onClick={()=>forceDlr(m.id)} className="bg-orange-600 text-white px-3 py-1 rounded text-xs">Force DELIVERED</button></td></tr>))}</tbody></table></div></div>}

        {/* MODALS */}
        {showTopup&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-96"><h3 className="font-semibold text-lg mb-4">Add Funds</h3><input type="number" placeholder="Amount" className="w-full bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm mb-3" value={topupAmt.amount} onChange={e=>setTopupAmt({...topupAmt,amount:e.target.value})}/><select className="w-full bg-black border border-gray-700 rounded-lg px-3 py-2 text-sm mb-3" value={topupAmt.method} onChange={e=>setTopupAmt({...topupAmt,method:e.target.value})}><option value="BANK_TRANSFER">Bank Transfer</option><option value="CREDIT_CARD">Credit Card</option><option value="PAYPAL">PayPal</option></select><div className="flex gap-2"><button onClick={topupClient} className="bg-emerald-600 px-4 py-2 rounded-lg text-sm flex-1">Confirm</button><button onClick={()=>setShowTopup(null)} className="bg-gray-700 px-4 py-2 rounded-lg text-sm">Cancel</button></div></div></div>}
        {showTx&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-gray-900 p-6 rounded-2xl border border-gray-700 w-[600px] max-h-[500px] overflow-auto"><h3 className="font-semibold text-lg mb-4">Payment History</h3><table className="w-full text-xs"><thead><tr className="border-b border-gray-800 text-gray-400"><th className="p-2">Date</th><th className="p-2">Type</th><th className="p-2">Amount</th></tr></thead><tbody>{txs.map(t=>(<tr key={t.id} className="border-b border-gray-800"><td className="p-2 text-gray-400">{new Date(t.createdAt).toLocaleString()}</td><td className="p-2"><span className={`px-2 py-0.5 rounded text-xs ${t.type==='TOPUP'?'bg-emerald-900 text-emerald-400':'bg-red-900 text-red-400'}`}>{t.type}</span></td><td className={`p-2 ${t.amount>0?'text-emerald-400':'text-red-400'}`}>${t.amount?.toFixed(2)}</td></tr>))}</tbody></table><button onClick={()=>setShowTx(null)} className="mt-4 bg-gray-700 px-4 py-2 rounded-lg text-sm w-full">Close</button></div></div>}
      </div>
    </div>
  );
}

export default App;
